apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/has-tests: true
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-sensors
  name: spring-sensors
spec:
  params:
  - name: gitops_branch
    value: stage
  - name: gitops_repository_name
    value: spring-sensors
  - name: gitops_repository_owner
    value: ynamadi
  - name: gitops_ssh_secret
    value: git-ssh
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/ynamadi/spring-sensors
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rmq-1