apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: spring-sensors-rmq
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    app.kubernetes.io/part-of: spring-sensors
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: spring-sensors
spec:
  name: rmq
  service:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: rmq-1
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: spring-sensors

